# Docker Compose configuration for sleepUp SpringBoot application

services:
  # SpringBoot application service
  sleepUp-app:
    # Build configuration - builds from local Dockerfile
    build:
      context: . # Build context is current directory
      dockerfile: Dockerfile # Use Dockerfile in current directory

    # Custom container name for easier identification
    container_name: sleepUp-springboot

    # Port mapping: host:container
    # Maps host port 8080 to container port 8080
    ports:
      - "8080:8080"

    # Environment variables passed to the SpringBoot application
    environment:
      SPRING_PROFILES_ACTIVE: docker # Activates Docker-specific configuration profile
      SERVER_PORT: 8080 # Sets the server port inside container
      DB_URL: jdbc:mysql://sleepUp-db:3306/sleepUp # Database connection URL using service name
      DB_USERNAME: ${DB_USERNAME} # Database username
      DB_PASSWORD: ${DB_PASSWORD} # Database password

    # Restart policy - restarts container unless explicitly stopped
    restart: unless-stopped

    # Service dependencies - ensures database is healthy before starting app
    depends_on:
      sleepUp-db:
        condition: service_healthy # Wait for DB health check to pass

    # Health check configuration for the SpringBoot application
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] # Health check command
      interval: 30s # Check every 30 seconds
      timeout: 10s # Timeout after 10 seconds
      retries: 3 # Retry 3 times before marking as unhealthy
      start_period: 60s # Wait 60 seconds before starting health checks

    # Connect to custom network
    networks:
      - sleepUp-network

  # MySQL database service
  sleepUp-db:
    # Use official MySQL 8.0 image from Docker Hub
    image: mysql:8.0

    # Custom container name for easier identification
    container_name: sleepUp-db

    # MySQL environment variables for database initialization
    environment:
      MYSQL_DATABASE: sleepUp # Creates database named 'sleepUp'
      MYSQL_USER: ${DB_USERNAME} # Creates user 'sleepUp'
      MYSQL_PASSWORD: ${DB_PASSWORD} # Sets password for 'sleepUp' user
      MYSQL_ROOT_PASSWORD: root123 # Sets root user password

    # Port mapping: host:container
    # Maps host port 3306 to container port 3306 for external access
    ports:
      - "3306:3306"

    # Volume mounting for data persistence
    # Maps named volume 'mysql_data' to MySQL data directory
    volumes:
      - mysql_data:/var/lib/mysql

    # Restart policy - restarts container unless explicitly stopped
    restart: unless-stopped

    # Health check configuration for MySQL database
    healthcheck:
      test: [
        "CMD",
        "mysqladmin", # MySQL admin utility
        "ping", # Ping command to check if MySQL is responding
        "-h",
        "localhost", # Connect to localhost
        "-u",
        "sleepUp", # Use sleepUp user for health check
        "-psleepUp123", # Password for sleepUp user
      ]
      interval: 10s # Check every 10 seconds
      timeout: 5s # Timeout after 5 seconds
      retries: 5 # Retry 5 times before marking as unhealthy
      start_period: 30s # Wait 30 seconds before starting health checks

    # Connect to custom network
    networks:
      - sleepUp-network

# Network configuration
networks:
  sleepUp-network:
    driver: bridge # Use bridge driver for container-to-container communication

# Volume configuration
volumes:
  mysql_data: # Named volume for MySQL data persistence